# Generated by Django 3.1.5 on 2021-01-30 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vilight', '0003_auto_20210130_1756'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
