# Generated by Django 3.1.5 on 2021-02-02 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vilight', '0005_axxxx'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendant',
            name='month',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
