# Generated by Django 3.1.5 on 2021-02-02 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vilight', '0007_attendant_admin_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendant',
            name='admin_comment',
            field=models.CharField(choices=[('0', 'Đã xử lý'), ('1', 'Chưa hợp lệ')], max_length=255, null=True),
        ),
    ]
